#! /usr/bin/env php
<?php
/**
 * Copyright (c) 2009-2012 [Ryan Parman](http://ryanparman.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * <http://www.opensource.org/licenses/mit-license.php>
 */


// Load the bootstrap
require_once __DIR__ . '/src/bootstrap.php';

// List the namespaces to use
use Symfony\Component\Console\Application;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Vanity\Config\Store as ConfigStore;
use Vanity\Event\Dispatcher;
use Vanity\System\Timer;


/********************************************************/
// INSTANTIATE CONSOLE APPLICATION

// Instantiate
Dispatcher::set(new EventDispatcher);
$console = new Application('Vanity', VANITY_VERSION);

$console->add(new Vanity\Command\PHP\Fetch);
$console->add(new Vanity\Command\Reference\Parse);

Timer::start();


/********************************************************/
// REGISTER GLOBAL EVENT HANDLERS

Vanity\Event\RegisterGlobal::events();


/********************************************************/
// RUN THE APPLICATION

$console->run();
